version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "house-price-lambda" 
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 149195854840.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --no-cache -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest 149195854840.dkr.ecr.eu-north-1.amazonaws.com/$IMAGE_REPO_NAME:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 149195854840.dkr.ecr.eu-north-1.amazonaws.com/$IMAGE_REPO_NAME:latest
