linear_regression:
  features:
    - size_num
    - bedrooms
    - year_of_construction
    - nr_rooms
    - bathrooms
    - toilets
    - contribution_vve_num
    - external_storage_num
    - inhabitants_in_neighborhood
    - families_with_children_pct
    - price_per_m2_neighborhood
    - energy_label
  target: price_num
  train_test_split:
    test_size: 0.2
    random_state: 42
  scaling:
    method: StandardScaler
    scale: true
  model_params:
    fit_intercept: true
  fit_params: {}
  search_space: {}

random_forest:
  features:
    - size_num
    - bedrooms
    - energy_label
    - year_of_construction
    - nr_rooms
    - bathrooms
    - toilets
    - contribution_vve_num
    - external_storage_num
    - has_mechanische_ventilatie
    - has_tv_kabel
    - has_lift
    - has_natuurlijke_ventilatie
    # - has_n/a
    - has_schuifpui
    - has_glasvezelkabel
    - has_frans_balkon
    - has_buitenzonwering
    - has_zonnepanelen
    - has_airconditioning
    - has_balansventilatie
    - has_dakraam
    - has_alarminstallatie
    - has_domotica
    - has_rookkanaal
    - has_elektra
    - has_sauna
    - has_zonnecollectoren
    - has_cctv
    - has_rolluiken
    - has_stromend_water
    - has_satellietschotel
    - num_facilities
    - inhabitants_in_neighborhood
    - families_with_children_pct
    - price_per_m2_neighborhood
  target: price_num
  train_test_split:
    test_size: 0.2
    random_state: 42
    val_required: false
  scaling:
    scale: false
  model_params:
    n_estimators: 200
    max_depth: 10
    random_state: 42
  fit_params: {}
  search_space:
    n_estimators:
      type: int
      low: 200
      high: 1000
    max_depth:
      type: int
      low: 5
      high: 30
    min_samples_split:
      type: int
      low: 2
      high: 20
    min_samples_leaf:
      type: int
      low: 2
      high: 8
    max_features:
      type: categorical
      choices: ["sqrt", "log2", null]

random_forest_optuna:
  features:
    - size_num
    - bedrooms
    - energy_label
    - year_of_construction
    - nr_rooms
    - bathrooms
    - toilets
    - contribution_vve_num
    - external_storage_num
    - has_mechanische_ventilatie
    - has_tv_kabel
    - has_lift
    - has_natuurlijke_ventilatie
    # - has_n/a
    - has_schuifpui
    - has_glasvezelkabel
    - has_frans_balkon
    - has_buitenzonwering
    - has_zonnepanelen
    - has_airconditioning
    - has_balansventilatie
    - has_dakraam
    - has_alarminstallatie
    - has_domotica
    - has_rookkanaal
    - has_elektra
    - has_sauna
    - has_zonnecollectoren
    - has_cctv
    - has_rolluiken
    - has_stromend_water
    - has_satellietschotel
    - num_facilities
    - inhabitants_in_neighborhood
    - families_with_children_pct
    - price_per_m2_neighborhood
  target: price_num
  train_test_split:
    test_size: 0.2
    random_state: 42
    val_required: true
  scaling:
    scale: false
  model_params:
    n_estimators: 200
    max_depth: 10
    n_jobs: -1
    random_state: 42
  fit_params: {}
  search_space:
    n_estimators:
      type: int
      low: 600
      high: 900
    max_depth:
      type: int
      low: 12
      high: 16
    min_samples_split:
      type: int
      low: 4
      high: 8
    min_samples_leaf:
      type: int
      low: 3
      high: 6
    max_features:
      type: categorical
      choices: ["sqrt", "log2"]

xgboost:
  features:
    - size_num
    - bedrooms
    - energy_label
    - year_of_construction
    - nr_rooms
    - bathrooms
    - toilets
    - contribution_vve_num
    - external_storage_num
    - has_mechanische_ventilatie
    - has_tv_kabel
    - has_lift
    - has_natuurlijke_ventilatie
    # - has_n/a
    - has_schuifpui
    - has_glasvezelkabel
    - has_frans_balkon
    - has_buitenzonwering
    - has_zonnepanelen
    - has_airconditioning
    - has_balansventilatie
    - has_dakraam
    - has_alarminstallatie
    - has_domotica
    - has_rookkanaal
    - has_elektra
    - has_sauna
    - has_zonnecollectoren
    - has_cctv
    - has_rolluiken
    - has_stromend_water
    - has_satellietschotel
    - num_facilities
    - inhabitants_in_neighborhood
    - families_with_children_pct
    - price_per_m2_neighborhood
  target: price_num
  train_test_split:
    test_size: 0.2
    random_state: 42
    val_required: false
  scaling:
    scale: false
  model_params:
    objective: reg:squarederror
    max_depth: 6
    eta: 0.05
    seed: 42
  fit_params:
    n_estimators: 500
  search_space:
    max_depth:
      type: int
      low: 3
      high: 8
    min_child_weight:
      type: int
      low: 1
      high: 10
    eta:
      type: float
      low: 0.01
      high: 0.2
      log: true
    subsample:
      type: float
      low: 0.6
      high: 0.95
    colsample_bytree:
      type: float
      low: 0.6
      high: 0.95
    gamma:
      type: float
      low: 0
      high: 2
    lambda:
      type: float
      low: 0.1
      high: 10.0
      log: true
    alpha:
      type: float
      low: 0.0
      high: 5.0
    max_bin:
      type: int
      low: 128
      high: 512

xgboost_early_stopping:
  features:
    - size_num
    - bedrooms
    - energy_label
    - year_of_construction
    - nr_rooms
    - bathrooms
    - toilets
    # - living_area
    - contribution_vve_num
    - external_storage_num
    - has_mechanische_ventilatie
    - has_tv_kabel
    - has_lift
    - has_natuurlijke_ventilatie
    # - has_n/a
    - has_schuifpui
    - has_glasvezelkabel
    - has_frans_balkon
    - has_buitenzonwering
    - has_zonnepanelen
    - has_airconditioning
    - has_balansventilatie
    - has_dakraam
    - has_alarminstallatie
    - has_domotica
    - has_rookkanaal
    - has_elektra
    - has_sauna
    - has_zonnecollectoren
    - has_cctv
    - has_rolluiken
    - has_stromend_water
    - has_satellietschotel
    - num_facilities
    - inhabitants_in_neighborhood
    - families_with_children_pct
    - price_per_m2_neighborhood
  target: price_num
  train_test_split:
    test_size: 0.2
    random_state: 42
    val_required: true
    val_size: 0.1
  scaling:
    scale: false
  model_params:
    objective: reg:squarederror
    max_depth: 6
    eta: 0.05
    seed: 42
  fit_params:
    num_boost_round: 1000
    early_stopping_rounds: 50
    verbose_eval: false
  search_space:
    max_depth:
      type: int
      low: 5
      high: 6               # Focus on deeper trees that worked best
    min_child_weight:
      type: int
      low: 6
      high: 8               # Around best 7
    eta:
      type: float
      low: 0.025
      high: 0.03            # Slightly narrower learning rate range
      log: true
    subsample:
      type: float
      low: 0.84
      high: 0.87            # Focused around best 0.846
    colsample_bytree:
      type: float
      low: 0.86
      high: 0.87            # Focused around best 0.869
    gamma:
      type: float
      low: 3.0
      high: 3.3             # Narrowed around best 3.12
    lambda:
      type: float
      low: 9.5
      high: 10.5            # Narrow L2 range around 10.05
      log: true
    alpha:
      type: float
      low: 4.2
      high: 4.5             # Narrow L1 range around 4.38
    max_bin:
      type: int
      low: 340
      high: 350             # Focused around best 348


xgboost_early_stopping_optuna_feature_eng:
  features:
    - size_num
    - bedrooms
    - energy_label
    - year_of_construction
    - nr_rooms
    - bathrooms
    - toilets
    - contribution_vve_num
    - external_storage_num
    - has_mechanische_ventilatie
    - has_tv_kabel
    - has_lift
    - has_natuurlijke_ventilatie
    # - has_n/a
    - has_schuifpui
    - has_glasvezelkabel
    - has_frans_balkon
    - has_buitenzonwering
    - has_zonnepanelen
    - has_airconditioning
    - has_balansventilatie
    - has_dakraam
    - has_alarminstallatie
    - has_domotica
    - has_rookkanaal
    - has_elektra
    - has_sauna
    - has_zonnecollectoren
    - has_cctv
    - has_rolluiken
    - has_stromend_water
    - has_satellietschotel
    - num_facilities
    - inhabitants_in_neighborhood
    - families_with_children_pct
    - price_per_m2_neighborhood
    # Extra columns for feature engineering
    - located_on
    - ownership_type
    - backyard
    - balcony
    - postal_code_clean
    - status
    - roof_type
    - location
    - garden
  target: price_num
  train_test_split:
    test_size: 0.2
    random_state: 42
    val_required: true
    val_size: 0.1
  scaling:
    scale: false
  model_params:
    objective: reg:squarederror
    seed: 42
  fit_params:
    num_boost_round: 1000
    early_stopping_rounds: 50
    verbose_eval: false
  search_space:
    max_depth:
      type: int
      low: 3
      high: 6
    min_child_weight:
      type: int
      low: 7
      high: 10         
    eta:
      type: float
      low: 0.12
      high: 0.18
      log: false
    subsample:
      type: float
      low: 0.75
      high: 0.9        # Reasonable range to prevent overfitting
    colsample_bytree:
      type: float
      low: 0.7
      high: 0.8       # Slightly reduced upper bound to stabilize trees
    gamma:
      type: float
      low: 0.0
      high: 0.1        # Regularization to prune splits
    lambda:
      type: float
      low: 0.03       # >0 for log scale
      high: 0.1
    alpha:
      type: float
      low: 0.04        # >0 for log scale
      high: 0.12
    max_bin:
      type: int
      low: 250
      high: 300        # Smaller bins can improve split precision


xgboost_early_stopping_optuna_feature_eng_geoloc_exp:
  features:
    - size_num
    - bedrooms
    - energy_label
    - year_of_construction
    - nr_rooms
    - bathrooms
    - toilets
    - contribution_vve_num
    - external_storage_num
    - has_mechanische_ventilatie
    - has_tv_kabel
    - has_lift
    - has_natuurlijke_ventilatie
    # - has_n/a
    - has_schuifpui
    - has_glasvezelkabel
    - has_frans_balkon
    - has_buitenzonwering
    - has_zonnepanelen
    - has_airconditioning
    - has_balansventilatie
    - has_dakraam
    - has_alarminstallatie
    - has_domotica
    - has_rookkanaal
    - has_elektra
    - has_sauna
    - has_zonnecollectoren
    - has_cctv
    - has_rolluiken
    - has_stromend_water
    - has_satellietschotel
    - num_facilities
    - inhabitants_in_neighborhood
    - families_with_children_pct
    - price_per_m2_neighborhood
    # Extra columns for feature engineering
    - located_on
    - ownership_type
    - backyard
    - balcony
    - postal_code_clean
    - status
    - roof_type
    - location
    - garden
    - address
  target: price_num
  train_test_split:
    test_size: 0.2
    random_state: 42
    val_required: true
    val_size: 0.1
  scaling:
    scale: false
  model_params:
    objective: reg:squarederror
    seed: 42
  fit_params:
    num_boost_round: 1000
    early_stopping_rounds: 50
    verbose_eval: false
  search_space:
    max_depth:
      type: int
      low: 3
      high: 6
    min_child_weight:
      type: int
      low: 5
      high: 8
    eta:
      type: float
      low: 0.1
      high: 0.18
      log: false
    subsample:
      type: float
      low: 0.7
      high: 0.90
    colsample_bytree:
      type: float
      low: 0.69
      high: 0.8
    gamma:
      type: float
      low: 0.1
      high: 0.15
    lambda:
      type: float
      low: 0.06
      high: 0.15
    alpha:
      type: float
      low: 0.14
      high: 0.2
    max_bin:
      type: int
      low: 200
      high: 300   # Smaller bins can improve split precision

random_forest_optuna_feature_eng:
  features:
    - size_num
    - bedrooms
    - energy_label
    - year_of_construction
    - nr_rooms
    - bathrooms
    - toilets
    - contribution_vve_num
    - external_storage_num
    - has_mechanische_ventilatie
    - has_tv_kabel
    - has_lift
    - has_natuurlijke_ventilatie
    # - has_n/a
    - has_schuifpui
    - has_glasvezelkabel
    - has_frans_balkon
    - has_buitenzonwering
    - has_zonnepanelen
    - has_airconditioning
    - has_balansventilatie
    - has_dakraam
    - has_alarminstallatie
    - has_domotica
    - has_rookkanaal
    - has_elektra
    - has_sauna
    - has_zonnecollectoren
    - has_cctv
    - has_rolluiken
    - has_stromend_water
    - has_satellietschotel
    - num_facilities
    - inhabitants_in_neighborhood
    - families_with_children_pct
    - price_per_m2_neighborhood
    # Extra columns for feature engineering
    - located_on
    - ownership_type
    - backyard
    - balcony
    - postal_code_clean
    - status
    - roof_type
    - location
    - garden
  target: price_num
  train_test_split:
    test_size: 0.2
    random_state: 42
    val_required: true
  scaling:
    scale: false
  model_params:
    n_estimators: 200
    max_depth: 10
    n_jobs: -1
    random_state: 42
  fit_params: {}
  search_space:
    n_estimators:
      type: int
      low: 200
      high: 600
    max_depth:
      type: int
      low: 12
      high: 22
    min_samples_split:
      type: int
      low: 2
      high: 8
    min_samples_leaf:
      type: int
      low: 2
      high: 3
    max_features:
      type: categorical
      choices: ["sqrt",  None]

      
geo_feature_exp:
  geo_cache_file: ../data/df_with_lat_lon_encoded.csv
  amenities_file: ../data/amsterdam_amenities.csv
  amenity_radius_map:
    school: [0.5, 1.0]
    park: [0.5, 1.0]
    supermarket: [0.5, 1.0]
    hospital: [1.0, 2.0]
    bus_stop: [0.5, 1.0]
    tram_stop: [0.5, 1.0]
    metro_stop: [0.5, 1.0]
    light_rail_stop: [0.5, 1.0]

production_model_name: XGB_Optuna_LogTransformed_feature_eng_best