preprocessing:
  drop_raw: false 
  numeric_cols:
    - bedrooms
    - nr_rooms
    - bathrooms
    - toilets
    - year_of_construction
  imputation:
    size_num: median
    external_storage_num: constant:0
    year_of_construction: median
    contribution_vve_num: constant:0